###############################################################################
# Created by write_sdc
###############################################################################
current_design core_riscv_superscalar
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 17.0000 [get_ports {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {cpu_enable}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[16]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[17]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[18]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[19]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[20]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[21]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[22]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[23]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[24]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[25]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[26]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[27]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[28]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[29]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[30]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[31]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rdata[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_ready}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[16]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[17]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[18]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[19]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[20]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[21]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[22]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[23]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[24]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[25]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[26]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[27]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[28]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[29]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[30]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[31]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata1[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[16]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[17]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[18]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[19]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[20]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[21]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[22]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[23]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[24]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[25]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[26]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[27]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[28]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[29]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[30]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[31]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_rdata2[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_ready}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst_n}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_halted}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instr[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_reg_data[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_addr[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_rd_en}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wdata[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wr_en}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wstrb[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wstrb[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wstrb[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {dmem_wstrb[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_addr[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {imem_req}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0300 [get_ports {debug_halted}]
set_load -pin_load 0.0300 [get_ports {dmem_rd_en}]
set_load -pin_load 0.0300 [get_ports {dmem_wr_en}]
set_load -pin_load 0.0300 [get_ports {imem_req}]
set_load -pin_load 0.0300 [get_ports {debug_instr[31]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[30]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[29]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[28]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[27]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[26]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[25]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[24]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[23]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[22]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[21]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[20]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[19]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[18]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[17]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[16]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[15]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[14]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[13]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[12]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[11]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[10]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[9]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[8]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[7]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[6]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[5]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[4]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[3]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[2]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[1]}]
set_load -pin_load 0.0300 [get_ports {debug_instr[0]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[31]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[30]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[29]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[28]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[27]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[26]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[25]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[24]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[23]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[22]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[21]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[20]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[19]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[18]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[17]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[16]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[15]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[14]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[13]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[12]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[11]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[10]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[9]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[8]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[7]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[6]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[5]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[4]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[3]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[2]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[1]}]
set_load -pin_load 0.0300 [get_ports {debug_pc[0]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[31]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[30]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[29]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[28]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[27]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[26]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[25]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[24]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[23]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[22]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[21]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[20]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[19]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[18]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[17]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[16]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[15]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[14]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[13]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[12]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[11]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[10]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[9]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[8]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[7]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[6]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[5]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[4]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[3]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[2]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[1]}]
set_load -pin_load 0.0300 [get_ports {debug_reg_data[0]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[31]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[30]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[29]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[28]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[27]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[26]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[25]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[24]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[23]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[22]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[21]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[20]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[19]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[18]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[17]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[16]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[15]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[14]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[13]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[12]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[11]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[10]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[9]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[8]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[7]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[6]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[5]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[4]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[3]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[2]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[1]}]
set_load -pin_load 0.0300 [get_ports {dmem_addr[0]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[31]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[30]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[29]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[28]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[27]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[26]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[25]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[24]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[23]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[22]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[21]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[20]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[19]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[18]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[17]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[16]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[15]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[14]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[13]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[12]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[11]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[10]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[9]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[8]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[7]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[6]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[5]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[4]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[3]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[2]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[1]}]
set_load -pin_load 0.0300 [get_ports {dmem_wdata[0]}]
set_load -pin_load 0.0300 [get_ports {dmem_wstrb[3]}]
set_load -pin_load 0.0300 [get_ports {dmem_wstrb[2]}]
set_load -pin_load 0.0300 [get_ports {dmem_wstrb[1]}]
set_load -pin_load 0.0300 [get_ports {dmem_wstrb[0]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[31]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[30]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[29]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[28]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[27]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[26]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[25]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[24]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[23]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[22]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[21]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[20]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[19]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[18]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[17]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[16]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[15]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[14]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[13]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[12]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[11]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[10]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[9]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[8]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[7]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[6]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[5]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[4]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[3]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[2]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[1]}]
set_load -pin_load 0.0300 [get_ports {imem_addr[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {cpu_enable}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_ready}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_ready}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst_n}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {dmem_rdata[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata1[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__buf_2 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {imem_rdata2[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 1.5000 [current_design]
set_max_fanout 20.0000 [current_design]
